/*
 jQuery JavaScript Library v3.3.1
 https://jquery.com/

 Includes Sizzle.js
 https://sizzlejs.com/

 Copyright JS Foundation and other contributors
 Released under the MIT license
 https://jquery.org/license

 Date: 2018-01-20T17:24Z
 Sizzle CSS Selector Engine v2.3.3
 https://sizzlejs.com/

 Copyright jQuery Foundation and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2016-08-08
*/
(function(t,ba){"object"===typeof module&&"object"===typeof module.exports?module.exports=t.document?ba(t,!0):function(t){if(!t.document)throw Error("jQuery requires a window with a document");return ba(t)}:ba(t)})("undefined"!==typeof window?window:this,function(t,ba){function fb(a,b,c){b=b||u;var e,d=b.createElement("script");d.text=a;if(c)for(e in Vb)c[e]&&(d[e]=c[e]);b.head.appendChild(d).parentNode.removeChild(d)}function la(a){return null==a?a+"":"object"===typeof a||"function"===typeof a?ca[gb.call(a)]||
"object":typeof a}function Qa(a){var b=!!a&&"length"in a&&a.length,c=la(a);return r(a)||ma(a)?!1:"array"===c||0===b||"number"===typeof b&&0<b&&b-1 in a}function E(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()}function Ra(a,b,c){return r(b)?d.grep(a,function(a,d){return!!b.call(a,d,a)!==c}):b.nodeType?d.grep(a,function(a){return a===b!==c}):"string"!==typeof b?d.grep(a,function(a){return-1<ua.call(b,a)!==c}):d.filter(b,a,c)}function hb(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}
function Wb(a){var b={};d.each(a.match(T)||[],function(a,e){b[e]=!0});return b}function na(a){return a}function za(a){throw a;}function ib(a,b,c,e){var d;try{a&&r(d=a.promise)?d.call(a).done(b).fail(c):a&&r(d=a.then)?d.call(a,b,c):b.apply(void 0,[a].slice(e))}catch(g){c.apply(void 0,[g])}}function Da(){u.removeEventListener("DOMContentLoaded",Da);t.removeEventListener("load",Da);d.ready()}function Xb(a,b){return b.toUpperCase()}function U(a){return a.replace(Yb,"ms-").replace(Zb,Xb)}function oa(){this.expando=
d.expando+oa.uid++}function jb(a,b,c){if(void 0===c&&1===a.nodeType)if(c="data-"+b.replace($b,"-$&").toLowerCase(),c=a.getAttribute(c),"string"===typeof c){try{var e=c;c="true"===e?!0:"false"===e?!1:"null"===e?null:e===+e+""?+e:ac.test(e)?JSON.parse(e):e}catch(f){}G.set(a,b,c)}else c=void 0;return c}function kb(a,b,c,e){var f,g=20,h=e?function(){return e.cur()}:function(){return d.css(a,b,"")},k=h(),l=c&&c[3]||(d.cssNumber[b]?"":"px"),m=(d.cssNumber[b]||"px"!==l&&+k)&&pa.exec(d.css(a,b));if(m&&m[3]!==
l){k/=2;l=l||m[3];for(m=+k||1;g--;)d.style(a,b,m+l),0>=(1-f)*(1-(f=h()/k||.5))&&(g=0),m/=f;m*=2;d.style(a,b,m+l);c=c||[]}if(c){m=+m||+k||0;var n=c[1]?m+(c[1]+1)*c[2]:+c[2];e&&(e.unit=l,e.start=m,e.end=n)}return n}function aa(a,b){for(var c,e,f=[],g=0,h=a.length;g<h;g++)if(e=a[g],e.style)if(c=e.style.display,b){if("none"===c&&(f[g]=v.get(e,"display")||null,f[g]||(e.style.display="")),""===e.style.display&&Ea(e)){c=g;var k=e.ownerDocument;e=e.nodeName;var l=lb[e];l||(k=k.body.appendChild(k.createElement(e)),
l=d.css(k,"display"),k.parentNode.removeChild(k),"none"===l&&(l="block"),lb[e]=l);k=l;f[c]=k}}else"none"!==c&&(f[g]="none",v.set(e,"display",c));for(g=0;g<h;g++)null!=f[g]&&(a[g].style.display=f[g]);return a}function H(a,b){var c="undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&E(a,b)?d.merge([a],c):c}function Sa(a,b){for(var c=0,e=a.length;c<e;c++)v.set(a[c],"globalEval",!b||v.get(b[c],
"globalEval"))}function mb(a,b,c,e,f){for(var g,h,k,l=b.createDocumentFragment(),m=[],n=0,q=a.length;n<q;n++)if((g=a[n])||0===g)if("object"===la(g))d.merge(m,g.nodeType?[g]:g);else if(bc.test(g)){h=h||l.appendChild(b.createElement("div"));k=(nb.exec(g)||["",""])[1].toLowerCase();k=N[k]||N._default;h.innerHTML=k[1]+d.htmlPrefilter(g)+k[2];for(k=k[0];k--;)h=h.lastChild;d.merge(m,h.childNodes);h=l.firstChild;h.textContent=""}else m.push(b.createTextNode(g));l.textContent="";for(n=0;g=m[n++];)if(e&&-1<
d.inArray(g,e))f&&f.push(g);else if(a=d.contains(g.ownerDocument,g),h=H(l.appendChild(g),"script"),a&&Sa(h),c)for(k=0;g=h[k++];)ob.test(g.type||"")&&c.push(g);return l}function Fa(){return!0}function qa(){return!1}function pb(){try{return u.activeElement}catch(a){}}function Ta(a,b,c,e,f,g){var h;if("object"===typeof b){"string"!==typeof c&&(e=e||c,c=void 0);for(h in b)Ta(a,h,c,e,b[h],g);return a}null==e&&null==f?(f=c,e=c=void 0):null==f&&("string"===typeof c?(f=e,e=void 0):(f=e,e=c,c=void 0));if(!1===
f)f=qa;else if(!f)return a;if(1===g){var k=f;f=function(a){d().off(a);return k.apply(this,arguments)};f.guid=k.guid||(k.guid=d.guid++)}return a.each(function(){d.event.add(this,b,f,e,c)})}function qb(a,b){return E(a,"table")&&E(11!==b.nodeType?b:b.firstChild,"tr")?d(a).children("tbody")[0]||a:a}function cc(a){a.type=(null!==a.getAttribute("type"))+"/"+a.type;return a}function dc(a){"true/"===(a.type||"").slice(0,5)?a.type=a.type.slice(5):a.removeAttribute("type");return a}function rb(a,b){var c;if(1===
b.nodeType){if(v.hasData(a)){var e=v.access(a);var f=v.set(b,e);if(e=e.events)for(g in delete f.handle,f.events={},e)for(f=0,c=e[g].length;f<c;f++)d.event.add(b,g,e[g][f])}if(G.hasData(a)){var g=G.access(a);g=d.extend({},g);G.set(b,g)}}}function ra(a,b,c,e){b=sb.apply([],b);var f,g=0,h=a.length,k=h-1,l=b[0],m=r(l);if(m||1<h&&"string"===typeof l&&!z.checkClone&&ec.test(l))return a.each(function(d){var f=a.eq(d);m&&(b[0]=l.call(this,d,f.html()));ra(f,b,c,e)});if(h){var n=mb(b,a[0].ownerDocument,!1,
a,e);var q=n.firstChild;1===n.childNodes.length&&(n=q);if(q||e){q=d.map(H(n,"script"),cc);for(f=q.length;g<h;g++){var p=n;g!==k&&(p=d.clone(p,!0,!0),f&&d.merge(q,H(p,"script")));c.call(a[g],p,g)}if(f)for(n=q[q.length-1].ownerDocument,d.map(q,dc),g=0;g<f;g++)p=q[g],ob.test(p.type||"")&&!v.access(p,"globalEval")&&d.contains(n,p)&&(p.src&&"module"!==(p.type||"").toLowerCase()?d._evalUrl&&d._evalUrl(p.src):fb(p.textContent.replace(fc,""),n,p))}}return a}function tb(a,b,c){for(var e=b?d.filter(b,a):a,
f=0;null!=(b=e[f]);f++)c||1!==b.nodeType||d.cleanData(H(b)),b.parentNode&&(c&&d.contains(b.ownerDocument,b)&&Sa(H(b,"script")),b.parentNode.removeChild(b));return a}function sa(a,b,c){var e=a.style;if(c=c||Ha(a)){var f=c.getPropertyValue(b)||c[b];""!==f||d.contains(a.ownerDocument,a)||(f=d.style(a,b));if(!z.pixelBoxStyles()&&Ua.test(f)&&gc.test(b)){a=e.width;b=e.minWidth;var g=e.maxWidth;e.minWidth=e.maxWidth=e.width=f;f=c.width;e.width=a;e.minWidth=b;e.maxWidth=g}}return void 0!==f?f+"":f}function ub(a,
b){return{get:function(){if(a())delete this.get;else return(this.get=b).apply(this,arguments)}}}function vb(a){var b=d.cssProps[a];if(!b){b=d.cssProps;a:{var c=a;if(!(c in wb)){for(var e=c[0].toUpperCase()+c.slice(1),f=xb.length;f--;)if(c=xb[f]+e,c in wb)break a;c=void 0}}b=b[a]=c||a}return b}function yb(a,b,c){return(a=pa.exec(b))?Math.max(0,a[2]-(c||0))+(a[3]||"px"):b}function Va(a,b,c,e,f,g){var h="width"===b?1:0,k=0,l=0;if(c===(e?"border":"content"))return 0;for(;4>h;h+=2)"margin"===c&&(l+=d.css(a,
c+I[h],!0,f)),e?("content"===c&&(l-=d.css(a,"padding"+I[h],!0,f)),"margin"!==c&&(l-=d.css(a,"border"+I[h]+"Width",!0,f))):(l+=d.css(a,"padding"+I[h],!0,f),"padding"!==c?l+=d.css(a,"border"+I[h]+"Width",!0,f):k+=d.css(a,"border"+I[h]+"Width",!0,f));!e&&0<=g&&(l+=Math.max(0,Math.ceil(a["offset"+b[0].toUpperCase()+b.slice(1)]-g-l-k-.5)));return l}function zb(a,b,c){var e=Ha(a),f=sa(a,b,e),g="border-box"===d.css(a,"boxSizing",!1,e),h=g;if(Ua.test(f)){if(!c)return f;f="auto"}h=h&&(z.boxSizingReliable()||
f===a.style[b]);if("auto"===f||!parseFloat(f)&&"inline"===d.css(a,"display",!1,e))f=a["offset"+b[0].toUpperCase()+b.slice(1)],h=!0;f=parseFloat(f)||0;return f+Va(a,b,c||(g?"border":"content"),h,e,f)+"px"}function B(a,b,c,e,d){return new B.prototype.init(a,b,c,e,d)}function Wa(){Ia&&(!1===u.hidden&&t.requestAnimationFrame?t.requestAnimationFrame(Wa):t.setTimeout(Wa,d.fx.interval),d.fx.tick())}function Ab(){t.setTimeout(function(){V=void 0});return V=Date.now()}function Ja(a,b){var c=0,e={height:a};
for(b=b?1:0;4>c;c+=2-b){var d=I[c];e["margin"+d]=e["padding"+d]=a}b&&(e.opacity=e.width=a);return e}function Bb(a,b,c){for(var e,d=(S.tweeners[b]||[]).concat(S.tweeners["*"]),g=0,h=d.length;g<h;g++)if(e=d[g].call(c,b,a))return e}function hc(a,b){var c,e;for(c in a){var f=U(c);var g=b[f];var h=a[c];Array.isArray(h)&&(g=h[1],h=a[c]=h[0]);c!==f&&(a[f]=h,delete a[c]);if((e=d.cssHooks[f])&&"expand"in e)for(c in h=e.expand(h),delete a[f],h)c in a||(a[c]=h[c],b[c]=g);else b[f]=g}}function S(a,b,c){var e,
f=0,g=S.prefilters.length,h=d.Deferred().always(function(){delete k.elem}),k=function(){if(e)return!1;var b=V||Ab();b=Math.max(0,l.startTime+l.duration-b);for(var c=1-(b/l.duration||0),d=0,f=l.tweens.length;d<f;d++)l.tweens[d].run(c);h.notifyWith(a,[l,c,b]);if(1>c&&f)return b;f||h.notifyWith(a,[l,1,0]);h.resolveWith(a,[l]);return!1},l=h.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{},easing:d.easing._default},c),originalProperties:b,originalOptions:c,startTime:V||Ab(),duration:c.duration,
tweens:[],createTween:function(b,c){var e=d.Tween(a,l.opts,b,c,l.opts.specialEasing[b]||l.opts.easing);l.tweens.push(e);return e},stop:function(b){var c=0,d=b?l.tweens.length:0;if(e)return this;for(e=!0;c<d;c++)l.tweens[c].run(1);b?(h.notifyWith(a,[l,1,0]),h.resolveWith(a,[l,b])):h.rejectWith(a,[l,b]);return this}});c=l.props;for(hc(c,l.opts.specialEasing);f<g;f++)if(b=S.prefilters[f].call(l,a,c,l.opts))return r(b.stop)&&(d._queueHooks(l.elem,l.opts.queue).stop=b.stop.bind(b)),b;d.map(c,Bb,l);r(l.opts.start)&&
l.opts.start.call(a,l);l.progress(l.opts.progress).done(l.opts.done,l.opts.complete).fail(l.opts.fail).always(l.opts.always);d.fx.timer(d.extend(k,{elem:a,anim:l,queue:l.opts.queue}));return l}function L(a){return(a.match(T)||[]).join(" ")}function da(a){return a.getAttribute&&a.getAttribute("class")||""}function Xa(a){return Array.isArray(a)?a:"string"===typeof a?a.match(T)||[]:[]}function Ya(a,b,c,e){var f;if(Array.isArray(b))d.each(b,function(b,d){c||ic.test(a)?e(a,d):Ya(a+"["+("object"===typeof d&&
null!=d?b:"")+"]",d,c,e)});else if(c||"object"!==la(b))e(a,b);else for(f in b)Ya(a+"["+f+"]",b[f],c,e)}function Cb(a){return function(b,c){"string"!==typeof b&&(c=b,b="*");var d,f=0,g=b.toLowerCase().match(T)||[];if(r(c))for(;d=g[f++];)"+"===d[0]?(d=d.slice(1)||"*",(a[d]=a[d]||[]).unshift(c)):(a[d]=a[d]||[]).push(c)}}function Db(a,b,c,e){function f(k){var l;g[k]=!0;d.each(a[k]||[],function(a,d){var k=d(b,c,e);if("string"===typeof k&&!h&&!g[k])return b.dataTypes.unshift(k),f(k),!1;if(h)return!(l=k)});
return l}var g={},h=a===Za;return f(b.dataTypes[0])||!g["*"]&&f("*")}function $a(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)void 0!==b[c]&&((f[c]?a:e||(e={}))[c]=b[c]);e&&d.extend(!0,a,e);return a}var W=[],u=t.document,jc=Object.getPrototypeOf,ea=W.slice,sb=W.concat,ab=W.push,ua=W.indexOf,ca={},gb=ca.toString,Ka=ca.hasOwnProperty,Eb=Ka.toString,kc=Eb.call(Object),z={},r=function(a){return"function"===typeof a&&"number"!==typeof a.nodeType},ma=function(a){return null!=a&&a===a.window},
Vb={type:!0,src:!0,noModule:!0},d=function(a,b){return new d.fn.init(a,b)},lc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;d.fn=d.prototype={jquery:"3.3.1",constructor:d,length:0,toArray:function(){return ea.call(this)},get:function(a){return null==a?ea.call(this):0>a?this[a+this.length]:this[a]},pushStack:function(a){a=d.merge(this.constructor(),a);a.prevObject=this;return a},each:function(a){return d.each(this,a)},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},slice:function(){return this.pushStack(ea.apply(this,
arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},end:function(){return this.prevObject||this.constructor()},push:ab,sort:W.sort,splice:W.splice};d.extend=d.fn.extend=function(){var a,b,c,e=arguments[0]||{},f=1,g=arguments.length,h=!1;"boolean"===typeof e&&(h=e,e=arguments[f]||{},f++);"object"===typeof e||r(e)||(e={});f===g&&(e=this,f--);for(;f<g;f++)if(null!=(a=arguments[f]))for(b in a){var k=
e[b];var l=a[b];e!==l&&(h&&l&&(d.isPlainObject(l)||(c=Array.isArray(l)))?(c?(c=!1,k=k&&Array.isArray(k)?k:[]):k=k&&d.isPlainObject(k)?k:{},e[b]=d.extend(h,k,l)):void 0!==l&&(e[b]=l))}return e};d.extend({expando:"jQuery"+("3.3.1"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isPlainObject:function(a){if(!a||"[object Object]"!==gb.call(a))return!1;a=jc(a);if(!a)return!0;a=Ka.call(a,"constructor")&&a.constructor;return"function"===typeof a&&Eb.call(a)===
kc},isEmptyObject:function(a){for(var b in a)return!1;return!0},globalEval:function(a){fb(a)},each:function(a,b){var c,d=0;if(Qa(a))for(c=a.length;d<c&&!1!==b.call(a[d],d,a[d]);d++);else for(d in a)if(!1===b.call(a[d],d,a[d]))break;return a},trim:function(a){return null==a?"":(a+"").replace(lc,"")},makeArray:function(a,b){var c=b||[];null!=a&&(Qa(Object(a))?d.merge(c,"string"===typeof a?[a]:a):ab.call(c,a));return c},inArray:function(a,b,c){return null==b?-1:ua.call(b,a,c)},merge:function(a,b){for(var c=
+b.length,d=0,f=a.length;d<c;d++)a[f++]=b[d];a.length=f;return a},grep:function(a,b,c){for(var d=[],f=0,g=a.length,h=!c;f<g;f++)c=!b(a[f],f),c!==h&&d.push(a[f]);return d},map:function(a,b,c){var d,f=0,g=[];if(Qa(a))for(d=a.length;f<d;f++){var h=b(a[f],f,c);null!=h&&g.push(h)}else for(f in a)h=b(a[f],f,c),null!=h&&g.push(h);return sb.apply([],g)},guid:1,support:z});"function"===typeof Symbol&&(d.fn[Symbol.iterator]=W[Symbol.iterator]);d.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),
function(a,b){ca["[object "+b+"]"]=b.toLowerCase()});var ja=function(a){function b(a,b,c,d){var e,f,g,y,h=b&&b.ownerDocument,w=b?b.nodeType:9;c=c||[];if("string"!==typeof a||!a||1!==w&&9!==w&&11!==w)return c;if(!d&&((b?b.ownerDocument||b:F)!==x&&va(b),b=b||x,X)){if(11!==w&&(y=ta.exec(a)))if(e=y[1])if(9===w)if(f=b.getElementById(e)){if(f.id===e)return c.push(f),c}else return c;else{if(h&&(f=h.getElementById(e))&&Ca(b,f)&&f.id===e)return c.push(f),c}else{if(y[2])return I.apply(c,b.getElementsByTagName(a)),
c;if((e=y[3])&&J.getElementsByClassName&&b.getElementsByClassName)return I.apply(c,b.getElementsByClassName(e)),c}if(!(!J.qsa||La[a+" "]||R&&R.test(a))){if(1!==w){h=b;var k=a}else if("object"!==b.nodeName.toLowerCase()){(g=b.getAttribute("id"))?g=g.replace(oa,pa):b.setAttribute("id",g=C);f=ca(a);for(e=f.length;e--;)f[e]="#"+g+" "+t(f[e]);k=f.join(",");h=ba.test(a)&&q(b.parentNode)||b}if(k)try{return I.apply(c,h.querySelectorAll(k)),c}catch(Pc){}finally{g===C&&b.removeAttribute("id")}}}return za(a.replace(W,
"$1"),b,c,d)}function c(){function a(c,d){b.push(c+" ")>D.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function d(a){a[C]=!0;return a}function f(a){var b=x.createElement("fieldset");try{return!!a(b)}catch(w){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){for(var c=a.split("|"),d=c.length;d--;)D.attrHandle[c[d]]=b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&a.sourceIndex-b.sourceIndex;if(d)return d;if(c)for(;c=c.nextSibling;)if(c===
b)return-1;return a?1:-1}function k(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function l(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function m(a){return function(b){return"form"in b?b.parentNode&&!1===b.disabled?"label"in b?"label"in b.parentNode?b.parentNode.disabled===a:b.disabled===a:b.isDisabled===a||b.isDisabled!==!a&&xa(b)===a:b.disabled===a:"label"in b?b.disabled===a:!1}}function n(a){return d(function(b){b=
+b;return d(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=c[e]))})})}function q(a){return a&&"undefined"!==typeof a.getElementsByTagName&&a}function p(){}function t(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function Ga(a,b,c){var d=b.dir,e=b.next,f=e||d,g=c&&"parentNode"===f,y=G++;return b.first?function(b,c,e){for(;b=b[d];)if(1===b.nodeType||g)return a(b,c,e);return!1}:function(b,c,h){var w,k=[fa,y];if(h)for(;b=b[d];){if((1===b.nodeType||g)&&
a(b,c,h))return!0}else for(;b=b[d];)if(1===b.nodeType||g){var l=b[C]||(b[C]={});l=l[b.uniqueID]||(l[b.uniqueID]={});if(e&&e===b.nodeName.toLowerCase())b=b[d]||b;else{if((w=l[f])&&w[0]===fa&&w[1]===y)return k[2]=w[2];l[f]=k;if(k[2]=a(b,c,h))return!0}}return!1}}function v(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function r(a,b,c,d,e){for(var f,g=[],h=0,y=a.length,w=null!=b;h<y;h++)if(f=a[h])if(!c||c(f,d,e))g.push(f),w&&b.push(h);return g}function u(a,
c,e,f,g,h){f&&!f[C]&&(f=u(f));g&&!g[C]&&(g=u(g,h));return d(function(d,h,y,w){var k,l=[],m=[],P=h.length,Q;if(!(Q=d)){Q=c||"*";for(var n=y.nodeType?[y]:y,Aa=[],Ba=0,q=n.length;Ba<q;Ba++)b(Q,n[Ba],Aa);Q=Aa}Q=!a||!d&&c?Q:r(Q,l,a,y,w);n=e?g||(d?a:P||f)?[]:h:Q;e&&e(Q,n,y,w);if(f){var p=r(n,m);f(p,[],y,w);for(y=p.length;y--;)if(k=p[y])n[m[y]]=!(Q[m[y]]=k)}if(d){if(g||a){if(g){p=[];for(y=n.length;y--;)(k=n[y])&&p.push(Q[y]=k);g(null,n=[],p,w)}for(y=n.length;y--;)(k=n[y])&&-1<(p=g?L(d,k):l[y])&&(d[p]=!(h[p]=
k))}}else n=r(n===h?n.splice(P,n.length):n),g?g(null,h,n,w):I.apply(h,n)})}function A(a){var b,c,d=a.length,e=D.relative[a[0].type];var f=e||D.relative[" "];for(var g=e?1:0,h=Ga(function(a){return a===b},f,!0),y=Ga(function(a){return-1<L(b,a)},f,!0),k=[function(a,c,d){a=!e&&(d||c!==Ma)||((b=c).nodeType?h(a,c,d):y(a,c,d));b=null;return a}];g<d;g++)if(f=D.relative[a[g].type])k=[Ga(v(k),f)];else{f=D.filter[a[g].type].apply(null,a[g].matches);if(f[C]){for(c=++g;c<d&&!D.relative[a[c].type];c++);return u(1<
g&&v(k),1<g&&t(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(W,"$1"),f,g<c&&A(a.slice(g,c)),c<d&&A(a=a.slice(c)),c<d&&t(a))}k.push(f)}return v(k)}function z(a,c){var e=0<c.length,f=0<a.length,g=function(d,g,h,y,k){var l,w,m=0,P="0",Q=d&&[],n=[],q=Ma,Aa=d||f&&D.find.TAG("*",k),p=fa+=null==q?1:Math.random()||.1,Ba=Aa.length;for(k&&(Ma=g===x||g||k);P!==Ba&&null!=(l=Aa[P]);P++){if(f&&l){var t=0;g||l.ownerDocument===x||(va(l),h=!X);for(;w=a[t++];)if(w(l,g||x,h)){y.push(l);break}k&&(fa=
p)}e&&((l=!w&&l)&&m--,d&&Q.push(l))}m+=P;if(e&&P!==m){for(t=0;w=c[t++];)w(Q,n,g,h);if(d){if(0<m)for(;P--;)Q[P]||n[P]||(n[P]=T.call(y));n=r(n)}I.apply(y,n);k&&!d&&0<n.length&&1<m+c.length&&b.uniqueSort(y)}k&&(fa=p,Ma=q);return Q};return e?d(g):g}var M,Ma,K,O,x,Y,X,R,wa,Na,Ca,C="sizzle"+1*new Date,F=a.document,fa=0,G=0,H=c(),B=c(),La=c(),N=function(a,b){a===b&&(O=!0);return 0},S={}.hasOwnProperty,E=[],T=E.pop,U=E.push,I=E.push,Z=E.slice,L=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;
return-1},da=RegExp("[\\x20\\t\\r\\n\\f]+","g"),W=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),ea=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ja=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,la=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]","g"),ma=/:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,
na=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,aa={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:/^\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\]/,PSEUDO:/^:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,
CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},qa=/^(?:input|select|textarea|button)$/i,ra=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,
ta=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ba=/[+~]/,ha=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),ia=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)},oa=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]/g,pa=function(a,b){return b?"\x00"===a?"\ufffd":a.slice(0,-1)+"\\"+a.charCodeAt(a.length-1).toString(16)+" ":"\\"+a},sa=function(){va()},xa=Ga(function(a){return!0===a.disabled&&("form"in
a||"label"in a)},{dir:"parentNode",next:"legend"});try{I.apply(E=Z.call(F.childNodes),F.childNodes),E[F.childNodes.length].nodeType}catch(y){I={apply:E.length?function(a,b){U.apply(a,Z.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}var J=b.support={};var ya=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};var va=b.setDocument=function(a){var b;a=a?a.ownerDocument||a:F;if(a===x||9!==a.nodeType||!a.documentElement)return x;
x=a;Y=x.documentElement;X=!ya(x);F!==x&&(b=x.defaultView)&&b.top!==b&&(b.addEventListener?b.addEventListener("unload",sa,!1):b.attachEvent&&b.attachEvent("onunload",sa));J.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});J.getElementsByTagName=f(function(a){a.appendChild(x.createComment(""));return!a.getElementsByTagName("*").length});J.getElementsByClassName=V.test(x.getElementsByClassName);J.getById=f(function(a){Y.appendChild(a).id=C;return!x.getElementsByName||!x.getElementsByName(C).length});
J.getById?(D.filter.ID=function(a){var b=a.replace(ha,ia);return function(a){return a.getAttribute("id")===b}},D.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&X){var c=b.getElementById(a);return c?[c]:[]}}):(D.filter.ID=function(a){var b=a.replace(ha,ia);return function(a){return(a="undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}},D.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&X){var c,d,e=b.getElementById(a);if(e){if((c=e.getAttributeNode("id"))&&
c.value===a)return[e];var f=b.getElementsByName(a);for(d=0;e=f[d++];)if((c=e.getAttributeNode("id"))&&c.value===a)return[e]}return[]}});D.find.TAG=J.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a);if(J.qsa)return b.querySelectorAll(a)}:function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f};D.find.CLASS=J.getElementsByClassName&&function(a,b){if("undefined"!==
typeof b.getElementsByClassName&&X)return b.getElementsByClassName(a)};wa=[];R=[];if(J.qsa=V.test(x.querySelectorAll))f(function(a){Y.appendChild(a).innerHTML="<a id='"+C+"'></a><select id='"+C+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&R.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||R.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll("[id~="+C+"-]").length||R.push("~=");a.querySelectorAll(":checked").length||R.push(":checked");a.querySelectorAll("a#"+C+"+*").length||R.push(".#.+[+~]")}),f(function(a){a.innerHTML="<a href='' disabled='disabled'></a><select disabled='disabled'><option/></select>";var b=x.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&R.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");2!==a.querySelectorAll(":enabled").length&&
R.push(":enabled",":disabled");Y.appendChild(a).disabled=!0;2!==a.querySelectorAll(":disabled").length&&R.push(":enabled",":disabled");a.querySelectorAll("*,:x");R.push(",.*:")});(J.matchesSelector=V.test(Na=Y.matches||Y.webkitMatchesSelector||Y.mozMatchesSelector||Y.oMatchesSelector||Y.msMatchesSelector))&&f(function(a){J.disconnectedMatch=Na.call(a,"*");Na.call(a,"[s!='']:x");wa.push("!=",":((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});
R=R.length&&new RegExp(R.join("|"));wa=wa.length&&new RegExp(wa.join("|"));Ca=(b=V.test(Y.compareDocumentPosition))||V.test(Y.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!!(d&&1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};N=b?function(a,b){if(a===b)return O=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;
if(c)return c;c=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):1;return c&1||!J.sortDetached&&b.compareDocumentPosition(a)===c?a===x||a.ownerDocument===F&&Ca(F,a)?-1:b===x||b.ownerDocument===F&&Ca(F,b)?1:K?L(K,a)-L(K,b):0:c&4?-1:1}:function(a,b){if(a===b)return O=!0,0;var c=0;var d=a.parentNode;var e=b.parentNode,f=[a],g=[b];if(!d||!e)return a===x?-1:b===x?1:d?-1:e?1:K?L(K,a)-L(K,b):0;if(d===e)return h(a,b);for(d=a;d=d.parentNode;)f.unshift(d);for(d=b;d=d.parentNode;)g.unshift(d);
for(;f[c]===g[c];)c++;return c?h(f[c],g[c]):f[c]===F?-1:g[c]===F?1:0};return x};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){(a.ownerDocument||a)!==x&&va(a);c=c.replace(la,"='$1']");if(!(!J.matchesSelector||!X||La[c+" "]||wa&&wa.test(c)||R&&R.test(c)))try{var d=Na.call(a,c);if(d||J.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(Q){}return 0<b(c,x,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==x&&va(a);return Ca(a,b)};b.attr=
function(a,b){(a.ownerDocument||a)!==x&&va(a);var c=D.attrHandle[b.toLowerCase()];c=c&&S.call(D.attrHandle,b.toLowerCase())?c(a,b,!X):void 0;return void 0!==c?c:J.attributes||!X?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.escape=function(a){return(a+"").replace(oa,pa)};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;O=!J.detectDuplicates;K=!J.sortStable&&a.slice(0);a.sort(N);if(O){for(;b=a[e++];)b===
a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}K=null;return a};var ka=b.getText=function(a){var b="",c=0;var d=a.nodeType;if(!d)for(;d=a[c++];)b+=ka(d);else if(1===d||9===d||11===d){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=ka(a)}else if(3===d||4===d)return a.nodeValue;return b};var D=b.selectors={cacheLength:50,createPseudo:d,match:aa,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",
first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(ha,ia);a[3]=(a[3]||a[4]||a[5]||"").replace(ha,ia);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(aa.CHILD.test(a[0]))return null;a[3]?a[2]=a[4]||a[5]||"":c&&
ma.test(c)&&(b=ca(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(ha,ia).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=H[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),H(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&
a.getAttribute("class")||"")}))},ATTR:function(a,c,d){return function(e){e=b.attr(e,a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(da," ")+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:
function(b,c,k){var l,m;c=f!==g?"nextSibling":"previousSibling";var y=b.parentNode,n=h&&b.nodeName.toLowerCase();k=!k&&!h;var w=!1;if(y){if(f){for(;c;){for(l=b;l=l[c];)if(h?l.nodeName.toLowerCase()===n:1===l.nodeType)return!1;var P=c="only"===a&&!P&&"nextSibling"}return!0}P=[g?y.firstChild:y.lastChild];if(g&&k){l=y;var q=l[C]||(l[C]={});q=q[l.uniqueID]||(q[l.uniqueID]={});w=q[a]||[];w=(m=w[0]===fa&&w[1])&&w[2];for(l=m&&y.childNodes[m];l=++m&&l&&l[c]||(w=m=0)||P.pop();)if(1===l.nodeType&&++w&&l===
b){q[a]=[fa,m,w];break}}else if(k&&(l=b,q=l[C]||(l[C]={}),q=q[l.uniqueID]||(q[l.uniqueID]={}),w=q[a]||[],w=m=w[0]===fa&&w[1]),!1===w)for(;(l=++m&&l&&l[c]||(w=m=0)||P.pop())&&((h?l.nodeName.toLowerCase()!==n:1!==l.nodeType)||!++w||(k&&(q=l[C]||(l[C]={}),q=q[l.uniqueID]||(q[l.uniqueID]={}),q[a]=[fa,w]),l!==b)););w-=e;return w===d||0===w%d&&0<=w/d}}},PSEUDO:function(a,c){var e=D.pseudos[a]||D.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);if(e[C])return e(c);if(1<e.length){var f=[a,a,
"",c];return D.setFilters.hasOwnProperty(a.toLowerCase())?d(function(a,b){for(var d,f=e(a,c),g=f.length;g--;)d=L(a,f[g]),a[d]=!(b[d]=f[g])}):function(a){return e(a,0,f)}}return e}},pseudos:{not:d(function(a){var b=[],c=[],e=ua(a.replace(W,"$1"));return e[C]?d(function(a,b,c,d){d=e(a,null,d,[]);for(var f=a.length;f--;)if(c=d[f])a[f]=!(b[f]=c)}):function(a,d,f){b[0]=a;e(b,null,f,c);b[0]=null;return!c.pop()}}),has:d(function(a){return function(c){return 0<b(a,c).length}}),contains:d(function(a){a=a.replace(ha,
ia);return function(b){return-1<(b.textContent||b.innerText||ka(b)).indexOf(a)}}),lang:d(function(a){na.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(ha,ia).toLowerCase();return function(b){var c;do if(c=X?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===Y},focus:function(a){return a===
x.activeElement&&(!x.hasFocus||x.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:m(!1),disabled:m(!0),checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!D.pseudos.empty(a)},header:function(a){return ra.test(a.nodeName)},input:function(a){return qa.test(a.nodeName)},
button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:n(function(){return[0]}),last:n(function(a,b){return[b-1]}),eq:n(function(a,b,c){return[0>c?c+b:c]}),even:n(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:n(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:n(function(a,b,c){for(b=
0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:n(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};D.pseudos.nth=D.pseudos.eq;for(M in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})D.pseudos[M]=k(M);for(M in{submit:!0,reset:!0})D.pseudos[M]=l(M);p.prototype=D.filters=D.pseudos;D.setFilters=new p;var ca=b.tokenize=function(a,c){var d,e,f,g,h;if(g=B[a+" "])return c?0:g.slice(0);g=a;var l=[];for(h=D.preFilter;g;){if(!k||(d=ea.exec(g)))d&&(g=g.slice(d[0].length)||g),l.push(e=[]);var k=!1;
if(d=ja.exec(g))k=d.shift(),e.push({value:k,type:d[0].replace(W," ")}),g=g.slice(k.length);for(f in D.filter)!(d=aa[f].exec(g))||h[f]&&!(d=h[f](d))||(k=d.shift(),e.push({value:k,type:f,matches:d}),g=g.slice(k.length));if(!k)break}return c?g.length:g?b.error(a):B(a,l).slice(0)};var ua=b.compile=function(a,b){var c,d=[],e=[],f=La[a+" "];if(!f){b||(b=ca(a));for(c=b.length;c--;)f=A(b[c]),f[C]?d.push(f):e.push(f);f=La(a,z(e,d));f.selector=a}return f};var za=b.select=function(a,b,c,d){var e,f,g,h="function"===
typeof a&&a,l=!d&&ca(a=h.selector||a);c=c||[];if(1===l.length){var k=l[0]=l[0].slice(0);if(2<k.length&&"ID"===(f=k[0]).type&&9===b.nodeType&&X&&D.relative[k[1].type]){b=(D.find.ID(f.matches[0].replace(ha,ia),b)||[])[0];if(!b)return c;h&&(b=b.parentNode);a=a.slice(k.shift().value.length)}for(e=aa.needsContext.test(a)?0:k.length;e--;){f=k[e];if(D.relative[g=f.type])break;if(g=D.find[g])if(d=g(f.matches[0].replace(ha,ia),ba.test(k[0].type)&&q(b.parentNode)||b)){k.splice(e,1);a=d.length&&t(k);if(!a)return I.apply(c,
d),c;break}}}(h||ua(a,l))(d,b,!X,c,!b||ba.test(a)&&q(b.parentNode)||b);return c};J.sortStable=C.split("").sort(N).join("")===C;J.detectDuplicates=!!O;va();J.sortDetached=f(function(a){return a.compareDocumentPosition(x.createElement("fieldset"))&1});f(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});J.attributes&&f(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value",
"");return""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});return b}(t);d.find=ja;d.expr=ja.selectors;d.expr[":"]=d.expr.pseudos;
d.uniqueSort=d.unique=ja.uniqueSort;d.text=ja.getText;d.isXMLDoc=ja.isXML;d.contains=ja.contains;d.escapeSelector=ja.escape;var ta=function(a,b,c){for(var e=[],f=void 0!==c;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},Fb=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},Gb=d.expr.match.needsContext,Hb=/^<([a-z][^\/\0>:\x20\t\r\n\f]*)[\x20\t\r\n\f]*\/?>(?:<\/\1>|)$/i;d.filter=function(a,b,c){var e=b[0];c&&(a=":not("+a+
")");return 1===b.length&&1===e.nodeType?d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,d.grep(b,function(a){return 1===a.nodeType}))};d.fn.extend({find:function(a){var b,c=this.length,e=this;if("string"!==typeof a)return this.pushStack(d(a).filter(function(){for(b=0;b<c;b++)if(d.contains(e[b],this))return!0}));var f=this.pushStack([]);for(b=0;b<c;b++)d.find(a,e[b],f);return 1<c?d.uniqueSort(f):f},filter:function(a){return this.pushStack(Ra(this,a||[],!1))},not:function(a){return this.pushStack(Ra(this,
a||[],!0))},is:function(a){return!!Ra(this,"string"===typeof a&&Gb.test(a)?d(a):a||[],!1).length}});var nc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]+))$/;(d.fn.init=function(a,b,c){if(!a)return this;c=c||oc;if("string"===typeof a){var e="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:nc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:u,!0)),Hb.test(e[1])&&d.isPlainObject(b))for(e in b)if(r(this[e]))this[e](b[e]);
else this.attr(e,b[e])}else if(a=u.getElementById(e[2]))this[0]=a,this.length=1;return this}return a.nodeType?(this[0]=a,this.length=1,this):r(a)?void 0!==c.ready?c.ready(a):a(d):d.makeArray(a,this)}).prototype=d.fn;var oc=d(u);var pc=/^(?:parents|prev(?:Until|All))/,qc={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;a<c;a++)if(d.contains(this,b[a]))return!0})},closest:function(a,b){var c,e=0,f=this.length,
g=[],h="string"!==typeof a&&d(a);if(!Gb.test(a))for(;e<f;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(h?-1<h.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.uniqueSort(g):g)},index:function(a){return a?"string"===typeof a?ua.call(d(a),this[0]):ua.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(d.uniqueSort(d.merge(this.get(),d(a,b))))},addBack:function(a){return this.add(null==
a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return ta(a,"parentNode")},parentsUntil:function(a,b,c){return ta(a,"parentNode",c)},next:function(a){return hb(a,"nextSibling")},prev:function(a){return hb(a,"previousSibling")},nextAll:function(a){return ta(a,"nextSibling")},prevAll:function(a){return ta(a,"previousSibling")},nextUntil:function(a,b,c){return ta(a,"nextSibling",c)},prevUntil:function(a,b,
c){return ta(a,"previousSibling",c)},siblings:function(a){return Fb((a.parentNode||{}).firstChild,a)},children:function(a){return Fb(a.firstChild)},contents:function(a){if(E(a,"iframe"))return a.contentDocument;E(a,"template")&&(a=a.content||a);return d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);"Until"!==a.slice(-5)&&(e=c);e&&"string"===typeof e&&(f=d.filter(e,f));1<this.length&&(qc[a]||d.uniqueSort(f),pc.test(a)&&f.reverse());return this.pushStack(f)}});var T=
/[^\x20\t\r\n\f]+/g;d.Callbacks=function(a){a="string"===typeof a?Wb(a):d.extend({},a);var b,c,e,f,g=[],h=[],k=-1,l=function(){f=f||a.once;for(e=b=!0;h.length;k=-1)for(c=h.shift();++k<g.length;)!1===g[k].apply(c[0],c[1])&&a.stopOnFalse&&(k=g.length,c=!1);a.memory||(c=!1);b=!1;f&&(g=c?[]:"")},m={add:function(){g&&(c&&!b&&(k=g.length-1,h.push(c)),function p(b){d.each(b,function(b,c){r(c)?a.unique&&m.has(c)||g.push(c):c&&c.length&&"string"!==la(c)&&p(c)})}(arguments),c&&!b&&l());return this},remove:function(){d.each(arguments,
function(a,b){for(var c;-1<(c=d.inArray(b,g,c));)g.splice(c,1),c<=k&&k--});return this},has:function(a){return a?-1<d.inArray(a,g):0<g.length},empty:function(){g&&(g=[]);return this},disable:function(){f=h=[];g=c="";return this},disabled:function(){return!g},lock:function(){f=h=[];c||b||(g=c="");return this},locked:function(){return!!f},fireWith:function(a,c){f||(c=c||[],c=[a,c.slice?c.slice():c],h.push(c),b||l());return this},fire:function(){m.fireWith(this,arguments);return this},fired:function(){return!!e}};
return m};d.extend({Deferred:function(a){var b=[["notify","progress",d.Callbacks("memory"),d.Callbacks("memory"),2],["resolve","done",d.Callbacks("once memory"),d.Callbacks("once memory"),0,"resolved"],["reject","fail",d.Callbacks("once memory"),d.Callbacks("once memory"),1,"rejected"]],c="pending",e={state:function(){return c},always:function(){f.done(arguments).fail(arguments);return this},"catch":function(a){return e.then(null,a)},pipe:function(){var a=arguments;return d.Deferred(function(c){d.each(b,
function(b,d){var e=r(a[d[4]])&&a[d[4]];f[d[1]](function(){var a=e&&e.apply(this,arguments);if(a&&r(a.promise))a.promise().progress(c.notify).done(c.resolve).fail(c.reject);else c[d[0]+"With"](this,e?[a]:arguments)})});a=null}).promise()},then:function(a,c,e){function f(a,b,c,e){return function(){var h=this,k=arguments,l=function(){if(!(a<g)){var d=c.apply(h,k);if(d===b.promise())throw new TypeError("Thenable self-resolution");var l=d&&("object"===typeof d||"function"===typeof d)&&d.then;r(l)?e?l.call(d,
f(g,b,na,e),f(g,b,za,e)):(g++,l.call(d,f(g,b,na,e),f(g,b,za,e),f(g,b,na,b.notifyWith))):(c!==na&&(h=void 0,k=[d]),(e||b.resolveWith)(h,k))}},m=e?l:function(){try{l()}catch(A){d.Deferred.exceptionHook&&d.Deferred.exceptionHook(A,m.stackTrace),a+1>=g&&(c!==za&&(h=void 0,k=[A]),b.rejectWith(h,k))}};a?m():(d.Deferred.getStackHook&&(m.stackTrace=d.Deferred.getStackHook()),t.setTimeout(m))}}var g=0;return d.Deferred(function(d){b[0][3].add(f(0,d,r(e)?e:na,d.notifyWith));b[1][3].add(f(0,d,r(a)?a:na));b[2][3].add(f(0,
d,r(c)?c:za))}).promise()},promise:function(a){return null!=a?d.extend(a,e):e}},f={};d.each(b,function(a,d){var g=d[2],h=d[5];e[d[1]]=g.add;h&&g.add(function(){c=h},b[3-a][2].disable,b[3-a][3].disable,b[0][2].lock,b[0][3].lock);g.add(d[3].fire);f[d[0]]=function(){f[d[0]+"With"](this===f?void 0:this,arguments);return this};f[d[0]+"With"]=g.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=arguments.length,c=b,e=Array(c),f=ea.call(arguments),g=d.Deferred(),h=function(a){return function(c){e[a]=
this;f[a]=1<arguments.length?ea.call(arguments):c;--b||g.resolveWith(e,f)}};if(1>=b&&(ib(a,g.done(h(c)).resolve,g.reject,!b),"pending"===g.state()||r(f[c]&&f[c].then)))return g.then();for(;c--;)ib(f[c],h(c),g.reject);return g.promise()}});var rc=/^(Eval|Internal|Range|Reference|Syntax|Type|URI)Error$/;d.Deferred.exceptionHook=function(a,b){t.console&&t.console.warn&&a&&rc.test(a.name)&&t.console.warn("jQuery.Deferred exception: "+a.message,a.stack,b)};d.readyException=function(a){t.setTimeout(function(){throw a;
})};var bb=d.Deferred();d.fn.ready=function(a){bb.then(a)["catch"](function(a){d.readyException(a)});return this};d.extend({isReady:!1,readyWait:1,ready:function(a){(!0===a?--d.readyWait:d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||bb.resolveWith(u,[d]))}});d.ready.then=bb.then;"complete"===u.readyState||"loading"!==u.readyState&&!u.documentElement.doScroll?t.setTimeout(d.ready):(u.addEventListener("DOMContentLoaded",Da),t.addEventListener("load",Da));var Z=function(a,b,c,e,f,g,h){var k=0,l=
a.length,m=null==c;if("object"===la(c))for(k in f=!0,c)Z(a,b,k,c[k],!0,g,h);else if(void 0!==e&&(f=!0,r(e)||(h=!0),m&&(h?(b.call(a,e),b=null):(m=b,b=function(a,b,c){return m.call(d(a),c)})),b))for(;k<l;k++)b(a[k],c,h?e:e.call(a[k],k,b(a[k],c)));return f?a:m?b.call(a):l?b(a[0],c):g},Yb=/^-ms-/,Zb=/-([a-z])/g,Oa=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};oa.uid=1;oa.prototype={cache:function(a){var b=a[this.expando];b||(b={},Oa(a)&&(a.nodeType?a[this.expando]=b:Object.defineProperty(a,
this.expando,{value:b,configurable:!0})));return b},set:function(a,b,c){var d;a=this.cache(a);if("string"===typeof b)a[U(b)]=c;else for(d in b)a[U(d)]=b[d];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][U(b)]},access:function(a,b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return this.get(a,b);this.set(a,b,c);return void 0!==c?c:b},remove:function(a,b){var c,e=a[this.expando];if(void 0!==e){if(void 0!==b)for(Array.isArray(b)?b=b.map(U):(b=U(b),
b=b in e?[b]:b.match(T)||[]),c=b.length;c--;)delete e[b[c]];if(void 0===b||d.isEmptyObject(e))a.nodeType?a[this.expando]=void 0:delete a[this.expando]}},hasData:function(a){a=a[this.expando];return void 0!==a&&!d.isEmptyObject(a)}};var v=new oa,G=new oa,ac=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,$b=/[A-Z]/g;d.extend({hasData:function(a){return G.hasData(a)||v.hasData(a)},data:function(a,b,c){return G.access(a,b,c)},removeData:function(a,b){G.remove(a,b)},_data:function(a,b,c){return v.access(a,b,c)},_removeData:function(a,
b){v.remove(a,b)}});d.fn.extend({data:function(a,b){var c,d=this[0],f=d&&d.attributes;if(void 0===a){if(this.length){var g=G.get(d);if(1===d.nodeType&&!v.get(d,"hasDataAttrs")){for(c=f.length;c--;)if(f[c]){var h=f[c].name;0===h.indexOf("data-")&&(h=U(h.slice(5)),jb(d,h,g[h]))}v.set(d,"hasDataAttrs",!0)}}return g}return"object"===typeof a?this.each(function(){G.set(this,a)}):Z(this,function(b){if(d&&void 0===b){var c=G.get(d,a);if(void 0!==c)return c;c=jb(d,a);if(void 0!==c)return c}else this.each(function(){G.set(this,
a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){G.remove(this,a)})}});d.extend({queue:function(a,b,c){if(a){b=(b||"fx")+"queue";var e=v.get(a,b);c&&(!e||Array.isArray(c)?e=v.access(a,b,d.makeArray(c)):e.push(c));return e||[]}},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),h=function(){d.dequeue(a,b)};"inprogress"===f&&(f=c.shift(),e--);f&&("fx"===b&&c.unshift("inprogress"),delete g.stop,f.call(a,h,g));
!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return v.get(a,c)||v.access(a,c,{empty:d.Callbacks("once memory").add(function(){v.remove(a,[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;"string"!==typeof a&&(b=a,a="fx",c--);return arguments.length<c?d.queue(this[0],a):void 0===b?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,
a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,h=this.length,k=function(){--e||f.resolveWith(g,[g])};"string"!==typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(c=v.get(g[h],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(k));k();return f.promise(b)}});var Ib=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,pa=new RegExp("^(?:([+-])=|)("+Ib+")([a-z%]*)$","i"),I=["Top","Right","Bottom","Left"],Ea=function(a,b){a=b||a;return"none"===a.style.display||
""===a.style.display&&d.contains(a.ownerDocument,a)&&"none"===d.css(a,"display")},Jb=function(a,b,c,d){var e,g={};for(e in b)g[e]=a.style[e],a.style[e]=b[e];c=c.apply(a,d||[]);for(e in b)a.style[e]=g[e];return c},lb={};d.fn.extend({show:function(){return aa(this,!0)},hide:function(){return aa(this)},toggle:function(a){return"boolean"===typeof a?a?this.show():this.hide():this.each(function(){Ea(this)?d(this).show():d(this).hide()})}});var Kb=/^(?:checkbox|radio)$/i,nb=/<([a-z][^\/\0>\x20\t\r\n\f]+)/i,
ob=/^$|^module$|\/(?:java|ecma)script/i,N={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};N.optgroup=N.option;N.tbody=N.tfoot=N.colgroup=N.caption=N.thead;N.th=N.td;var bc=/<|&#?\w+;/;(function(){var a=u.createDocumentFragment().appendChild(u.createElement("div")),b=u.createElement("input");b.setAttribute("type",
"radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);z.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";z.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue})();var Pa=u.documentElement,sc=/^key/,tc=/^(?:mouse|pointer|contextmenu|drag|drop)|click/,Lb=/^([^.]*)(?:\.(.+)|)/;d.event={global:{},add:function(a,b,c,e,f){var g,h,k,l,m;if(k=v.get(a)){if(c.handler){var n=c;c=n.handler;f=n.selector}f&&d.find.matchesSelector(Pa,
f);c.guid||(c.guid=d.guid++);(h=k.events)||(h=k.events={});(g=k.handle)||(g=k.handle=function(b){return"undefined"!==typeof d&&d.event.triggered!==b.type?d.event.dispatch.apply(a,arguments):void 0});b=(b||"").match(T)||[""];for(k=b.length;k--;){var q=Lb.exec(b[k])||[];var p=l=q[1];var t=(q[2]||"").split(".").sort();p&&(q=d.event.special[p]||{},p=(f?q.delegateType:q.bindType)||p,q=d.event.special[p]||{},l=d.extend({type:p,origType:l,data:e,handler:c,guid:c.guid,selector:f,needsContext:f&&d.expr.match.needsContext.test(f),
namespace:t.join(".")},n),(m=h[p])||(m=h[p]=[],m.delegateCount=0,q.setup&&!1!==q.setup.call(a,e,t,g)||a.addEventListener&&a.addEventListener(p,g)),q.add&&(q.add.call(a,l),l.handler.guid||(l.handler.guid=c.guid)),f?m.splice(m.delegateCount++,0,l):m.push(l),d.event.global[p]=!0)}}},remove:function(a,b,c,e,f){var g,h,k,l,m,n=v.hasData(a)&&v.get(a);if(n&&(k=n.events)){b=(b||"").match(T)||[""];for(l=b.length;l--;){var q=Lb.exec(b[l])||[];var p=m=q[1];var t=(q[2]||"").split(".").sort();if(p){var r=d.event.special[p]||
{};p=(e?r.delegateType:r.bindType)||p;var u=k[p]||[];q=q[2]&&new RegExp("(^|\\.)"+t.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=u.length;g--;){var z=u[g];!f&&m!==z.origType||c&&c.guid!==z.guid||q&&!q.test(z.namespace)||e&&e!==z.selector&&("**"!==e||!z.selector)||(u.splice(g,1),z.selector&&u.delegateCount--,r.remove&&r.remove.call(a,z))}h&&!u.length&&(r.teardown&&!1!==r.teardown.call(a,t,n.handle)||d.removeEvent(a,p,n.handle),delete k[p])}else for(p in k)d.event.remove(a,p+b[l],c,e,!0)}d.isEmptyObject(k)&&
v.remove(a,"handle events")}},dispatch:function(a){var b=d.event.fix(a),c,e,f,g=Array(arguments.length);var h=(v.get(this,"events")||{})[b.type]||[];var k=d.event.special[b.type]||{};g[0]=b;for(c=1;c<arguments.length;c++)g[c]=arguments[c];b.delegateTarget=this;if(!k.preDispatch||!1!==k.preDispatch.call(this,b)){var l=d.event.handlers.call(this,b,h);for(c=0;(f=l[c++])&&!b.isPropagationStopped();)for(b.currentTarget=f.elem,h=0;(e=f.handlers[h++])&&!b.isImmediatePropagationStopped();)if(!b.rnamespace||
b.rnamespace.test(e.namespace))b.handleObj=e,b.data=e.data,e=((d.event.special[e.origType]||{}).handle||e.handler).apply(f.elem,g),void 0!==e&&!1===(b.result=e)&&(b.preventDefault(),b.stopPropagation());k.postDispatch&&k.postDispatch.call(this,b);return b.result}},handlers:function(a,b){var c,e=[],f=b.delegateCount,g=a.target;if(f&&g.nodeType&&!("click"===a.type&&1<=a.button))for(;g!==this;g=g.parentNode||this)if(1===g.nodeType&&("click"!==a.type||!0!==g.disabled)){var h=[];var k={};for(c=0;c<f;c++){var l=
b[c];var m=l.selector+" ";void 0===k[m]&&(k[m]=l.needsContext?-1<d(m,this).index(g):d.find(m,this,null,[g]).length);k[m]&&h.push(l)}h.length&&e.push({elem:g,handlers:h})}f<b.length&&e.push({elem:this,handlers:b.slice(f)});return e},addProp:function(a,b){Object.defineProperty(d.Event.prototype,a,{enumerable:!0,configurable:!0,get:r(b)?function(){if(this.originalEvent)return b(this.originalEvent)}:function(){if(this.originalEvent)return this.originalEvent[a]},set:function(b){Object.defineProperty(this,
a,{enumerable:!0,configurable:!0,writable:!0,value:b})}})},fix:function(a){return a[d.expando]?a:new d.Event(a)},special:{load:{noBubble:!0},focus:{trigger:function(){if(this!==pb()&&this.focus)return this.focus(),!1},delegateType:"focusin"},blur:{trigger:function(){if(this===pb()&&this.blur)return this.blur(),!1},delegateType:"focusout"},click:{trigger:function(){if("checkbox"===this.type&&this.click&&E(this,"input"))return this.click(),!1},_default:function(a){return E(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==
a.result&&a.originalEvent&&(a.originalEvent.returnValue=a.result)}}}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c)};d.Event=function(a,b){if(!(this instanceof d.Event))return new d.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||void 0===a.defaultPrevented&&!1===a.returnValue?Fa:qa,this.target=a.target&&3===a.target.nodeType?a.target.parentNode:a.target,this.currentTarget=a.currentTarget,this.relatedTarget=
a.relatedTarget):this.type=a;b&&d.extend(this,b);this.timeStamp=a&&a.timeStamp||Date.now();this[d.expando]=!0};d.Event.prototype={constructor:d.Event,isDefaultPrevented:qa,isPropagationStopped:qa,isImmediatePropagationStopped:qa,isSimulated:!1,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=Fa;a&&!this.isSimulated&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=Fa;a&&!this.isSimulated&&a.stopPropagation()},stopImmediatePropagation:function(){var a=
this.originalEvent;this.isImmediatePropagationStopped=Fa;a&&!this.isSimulated&&a.stopImmediatePropagation();this.stopPropagation()}};d.each({altKey:!0,bubbles:!0,cancelable:!0,changedTouches:!0,ctrlKey:!0,detail:!0,eventPhase:!0,metaKey:!0,pageX:!0,pageY:!0,shiftKey:!0,view:!0,"char":!0,charCode:!0,key:!0,keyCode:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pointerId:!0,pointerType:!0,screenX:!0,screenY:!0,targetTouches:!0,toElement:!0,touches:!0,which:function(a){var b=a.button;
return null==a.which&&sc.test(a.type)?null!=a.charCode?a.charCode:a.keyCode:!a.which&&void 0!==b&&tc.test(a.type)?b&1?1:b&2?3:b&4?2:0:a.which}},d.event.addProp);d.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var c=a.relatedTarget,f=a.handleObj;if(!c||c!==this&&!d.contains(this,c)){a.type=f.origType;var g=f.handler.apply(this,arguments);a.type=b}return g}}});d.fn.extend({on:function(a,
b,c,d){return Ta(this,a,b,c,d)},one:function(a,b,c,d){return Ta(this,a,b,c,d,1)},off:function(a,b,c){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if("object"===typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)c=b,b=void 0;!1===c&&(c=qa);return this.each(function(){d.event.remove(this,a,c,b)})}});var uc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([a-z][^\/\0>\x20\t\r\n\f]*)[^>]*)\/>/gi,
vc=/<script|<style|<link/i,ec=/checked\s*(?:[^=]|=\s*.checked.)/i,fc=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;d.extend({htmlPrefilter:function(a){return a.replace(uc,"<$1></$2>")},clone:function(a,b,c){var e,f=a.cloneNode(!0),g=d.contains(a.ownerDocument,a);if(!(z.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a))){var h=H(f);var k=H(a);var l=0;for(e=k.length;l<e;l++){var m=k[l],n=h[l],q=n.nodeName.toLowerCase();if("input"===q&&Kb.test(m.type))n.checked=m.checked;else if("input"===
q||"textarea"===q)n.defaultValue=m.defaultValue}}if(b)if(c)for(k=k||H(a),h=h||H(f),l=0,e=k.length;l<e;l++)rb(k[l],h[l]);else rb(a,f);h=H(f,"script");0<h.length&&Sa(h,!g&&H(a,"script"));return f},cleanData:function(a){for(var b,c,e,f=d.event.special,g=0;void 0!==(c=a[g]);g++)if(Oa(c)){if(b=c[v.expando]){if(b.events)for(e in b.events)f[e]?d.event.remove(c,e):d.removeEvent(c,e,b.handle);c[v.expando]=void 0}c[G.expando]&&(c[G.expando]=void 0)}}});d.fn.extend({detach:function(a){return tb(this,a,!0)},
remove:function(a){return tb(this,a)},text:function(a){return Z(this,function(a){return void 0===a?d.text(this):this.empty().each(function(){if(1===this.nodeType||11===this.nodeType||9===this.nodeType)this.textContent=a})},null,a,arguments.length)},append:function(){return ra(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||qb(this,a).appendChild(a)})},prepend:function(){return ra(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=
qb(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return ra(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return ra(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(H(a,!1)),a.textContent="");return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return d.clone(this,a,
b)})},html:function(a){return Z(this,function(a){var b=this[0]||{},e=0,f=this.length;if(void 0===a&&1===b.nodeType)return b.innerHTML;if("string"===typeof a&&!vc.test(a)&&!N[(nb.exec(a)||["",""])[1].toLowerCase()]){a=d.htmlPrefilter(a);try{for(;e<f;e++)b=this[e]||{},1===b.nodeType&&(d.cleanData(H(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=[];return ra(this,arguments,function(b){var c=this.parentNode;0>d.inArray(this,a)&&(d.cleanData(H(this)),
c&&c.replaceChild(b,this))},a)}});d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var c=[],f=d(a),g=f.length-1,h=0;h<=g;h++)a=h===g?this:this.clone(!0),d(f[h])[b](a),ab.apply(c,a.get());return this.pushStack(c)}});var Ua=new RegExp("^("+Ib+")(?!px)[a-z%]+$","i"),Ha=function(a){var b=a.ownerDocument.defaultView;b&&b.opener||(b=t);return b.getComputedStyle(a)},gc=new RegExp(I.join("|"),"i");(function(){function a(){if(k){h.style.cssText=
"position:absolute;left:-11111px;width:60px;margin-top:1px;padding:0;border:0";k.style.cssText="position:relative;display:block;box-sizing:border-box;overflow:scroll;margin:auto;border:1px;padding:1px;width:60%;top:1%";Pa.appendChild(h).appendChild(k);var a=t.getComputedStyle(k);b="1%"!==a.top;g=12===Math.round(parseFloat(a.marginLeft));k.style.right="60%";f=36===Math.round(parseFloat(a.right));c=36===Math.round(parseFloat(a.width));k.style.position="absolute";e=36===k.offsetWidth||"absolute";Pa.removeChild(h);
k=null}}var b,c,e,f,g,h=u.createElement("div"),k=u.createElement("div");k.style&&(k.style.backgroundClip="content-box",k.cloneNode(!0).style.backgroundClip="",z.clearCloneStyle="content-box"===k.style.backgroundClip,d.extend(z,{boxSizingReliable:function(){a();return c},pixelBoxStyles:function(){a();return f},pixelPosition:function(){a();return b},reliableMarginLeft:function(){a();return g},scrollboxSize:function(){a();return e}}))})();var wc=/^(none|table(?!-c[ea]).+)/,Mb=/^--/,xc={position:"absolute",
visibility:"hidden",display:"block"},Nb={letterSpacing:"0",fontWeight:"400"},xb=["Webkit","Moz","ms"],wb=u.createElement("div").style;d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=sa(a,"opacity");return""===c?"1":c}}}},cssNumber:{animationIterationCount:!0,columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,
g=U(b),h=Mb.test(b),k=a.style;h||(b=vb(g));var l=d.cssHooks[b]||d.cssHooks[g];if(void 0!==c){var m=typeof c;"string"===m&&(f=pa.exec(c))&&f[1]&&(c=kb(a,b,f),m="number");null!=c&&c===c&&("number"===m&&(c+=f&&f[3]||(d.cssNumber[g]?"":"px")),z.clearCloneStyle||""!==c||0!==b.indexOf("background")||(k[b]="inherit"),l&&"set"in l&&void 0===(c=l.set(a,c,e))||(h?k.setProperty(b,c):k[b]=c))}else return l&&"get"in l&&void 0!==(f=l.get(a,!1,e))?f:k[b]}},css:function(a,b,c,e){var f;var g=U(b);Mb.test(b)||(b=vb(g));
(g=d.cssHooks[b]||d.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,c));void 0===f&&(f=sa(a,b,e));"normal"===f&&b in Nb&&(f=Nb[b]);return""===c||c?(a=parseFloat(f),!0===c||isFinite(a)?a||0:f):f}});d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){if(e)return!wc.test(d.css(a,"display"))||a.getClientRects().length&&a.getBoundingClientRect().width?zb(a,b,f):Jb(a,xc,function(){return zb(a,b,f)})},set:function(a,e,f){var c,h=Ha(a),k="border-box"===d.css(a,"boxSizing",!1,h);f=f&&Va(a,b,
f,k,h);k&&z.scrollboxSize()===h.position&&(f-=Math.ceil(a["offset"+b[0].toUpperCase()+b.slice(1)]-parseFloat(h[b])-Va(a,b,"border",!1,h)-.5));f&&(c=pa.exec(e))&&"px"!==(c[3]||"px")&&(a.style[b]=e,e=d.css(a,b));return yb(a,e,f)}}});d.cssHooks.marginLeft=ub(z.reliableMarginLeft,function(a,b){if(b)return(parseFloat(sa(a,"marginLeft"))||a.getBoundingClientRect().left-Jb(a,{marginLeft:0},function(){return a.getBoundingClientRect().left}))+"px"});d.each({margin:"",padding:"",border:"Width"},function(a,
b){d.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>d;d++)f[a+I[d]+b]=c[d]||c[d-2]||c[0];return f}};"margin"!==a&&(d.cssHooks[a+b].set=yb)});d.fn.extend({css:function(a,b){return Z(this,function(a,b,f){var c,e={},k=0;if(Array.isArray(b)){f=Ha(a);for(c=b.length;k<c;k++)e[b[k]]=d.css(a,b[k],!1,f);return e}return void 0!==f?d.style(a,b,f):d.css(a,b)},a,b,1<arguments.length)}});d.Tween=B;B.prototype={constructor:B,init:function(a,b,c,e,f,g){this.elem=a;this.prop=
c;this.easing=f||d.easing._default;this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=B.propHooks[this.prop];return a&&a.get?a.get(this):B.propHooks._default.get(this)},run:function(a){var b,c=B.propHooks[this.prop];this.pos=this.options.duration?b=d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,this);
c&&c.set?c.set(this):B.propHooks._default.set(this);return this}};B.prototype.init.prototype=B.prototype;B.propHooks={_default:{get:function(a){return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(a=d.css(a.elem,a.prop,""))&&"auto"!==a?a:0},set:function(a){if(d.fx.step[a.prop])d.fx.step[a.prop](a);else 1!==a.elem.nodeType||null==a.elem.style[d.cssProps[a.prop]]&&!d.cssHooks[a.prop]?a.elem[a.prop]=a.now:d.style(a.elem,a.prop,a.now+a.unit)}}};B.propHooks.scrollTop=
B.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};d.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};d.fx=B.prototype.init;d.fx.step={};var V,Ia,yc=/^(?:toggle|show|hide)$/,zc=/queueHooks$/;d.Animation=d.extend(S,{tweeners:{"*":[function(a,b){var c=this.createTween(a,b);kb(c.elem,a,pa.exec(b),c);return c}]},tweener:function(a,b){r(a)?(b=a,a=["*"]):a=a.match(T);for(var c,d=0,f=a.length;d<f;d++)c=
a[d],S.tweeners[c]=S.tweeners[c]||[],S.tweeners[c].unshift(b)},prefilters:[function(a,b,c){var e;var f="width"in b||"height"in b;var g=this,h={},k=a.style,l=a.nodeType&&Ea(a),m=v.get(a,"fxshow");if(!c.queue){var n=d._queueHooks(a,"fx");if(null==n.unqueued){n.unqueued=0;var q=n.empty.fire;n.empty.fire=function(){n.unqueued||q()}}n.unqueued++;g.always(function(){g.always(function(){n.unqueued--;d.queue(a,"fx").length||n.empty.fire()})})}for(e in b){var p=b[e];if(yc.test(p)){delete b[e];var t=t||"toggle"===
p;if(p===(l?"hide":"show"))if("show"===p&&m&&void 0!==m[e])l=!0;else continue;h[e]=m&&m[e]||d.style(a,e)}}if((b=!d.isEmptyObject(b))||!d.isEmptyObject(h)){if(f&&1===a.nodeType){c.overflow=[k.overflow,k.overflowX,k.overflowY];var r=m&&m.display;null==r&&(r=v.get(a,"display"));f=d.css(a,"display");"none"===f&&(r?f=r:(aa([a],!0),r=a.style.display||r,f=d.css(a,"display"),aa([a])));("inline"===f||"inline-block"===f&&null!=r)&&"none"===d.css(a,"float")&&(b||(g.done(function(){k.display=r}),null==r&&(f=
k.display,r="none"===f?"":f)),k.display="inline-block")}c.overflow&&(k.overflow="hidden",g.always(function(){k.overflow=c.overflow[0];k.overflowX=c.overflow[1];k.overflowY=c.overflow[2]}));b=!1;for(e in h)b||(m?"hidden"in m&&(l=m.hidden):m=v.access(a,"fxshow",{display:r}),t&&(m.hidden=!l),l&&aa([a],!0),g.done(function(){l||aa([a]);v.remove(a,"fxshow");for(e in h)d.style(a,e,h[e])})),b=Bb(l?m[e]:0,e,g),e in m||(m[e]=b.start,l&&(b.end=b.start,b.start=0))}}],prefilter:function(a,b){b?S.prefilters.unshift(a):
S.prefilters.push(a)}});d.speed=function(a,b,c){var e=a&&"object"===typeof a?d.extend({},a):{complete:c||!c&&b||r(a)&&a,duration:a,easing:c&&b||b&&!r(b)&&b};d.fx.off?e.duration=0:"number"!==typeof e.duration&&(e.duration=e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default);if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){r(e.old)&&e.old.call(this);e.queue&&d.dequeue(this,e.queue)};return e};d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(Ea).css("opacity",
0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){var f=d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var b=S(this,d.extend({},a),g);(f||v.get(this,"finish"))&&b.stop(!0)};b.finish=b;return f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(a){var b=a.stop;delete a.stop;b(c)};"string"!==typeof a&&(c=b,b=a,a=void 0);b&&!1!==a&&this.queue(a||"fx",[]);return this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=d.timers,k=v.get(this);if(g)k[g]&&
k[g].stop&&e(k[g]);else for(g in k)k[g]&&k[g].stop&&zc.test(g)&&e(k[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(c),b=!1,h.splice(g,1));!b&&c||d.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b=v.get(this),c=b[a+"queue"];var e=b[a+"queueHooks"];var f=d.timers,g=c?c.length:0;b.finish=!0;d.queue(this,a,[]);e&&e.stop&&e.stop.call(this,!0);for(e=f.length;e--;)f[e].elem===this&&f[e].queue===a&&(f[e].anim.stop(!0),f.splice(e,
1));for(e=0;e<g;e++)c[e]&&c[e].finish&&c[e].finish.call(this);delete b.finish})}});d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==a||"boolean"===typeof a?c.apply(this,arguments):this.animate(Ja(b,!0),a,d,g)}});d.each({slideDown:Ja("show"),slideUp:Ja("hide"),slideToggle:Ja("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.timers=[];d.fx.tick=
function(){var a=0,b=d.timers;for(V=Date.now();a<b.length;a++){var c=b[a];c()||b[a]!==c||b.splice(a--,1)}b.length||d.fx.stop();V=void 0};d.fx.timer=function(a){d.timers.push(a);d.fx.start()};d.fx.interval=13;d.fx.start=function(){Ia||(Ia=!0,Wa())};d.fx.stop=function(){Ia=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fn.delay=function(a,b){a=d.fx?d.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,d){var c=t.setTimeout(b,a);d.stop=function(){t.clearTimeout(c)}})};(function(){var a=u.createElement("input"),
b=u.createElement("select").appendChild(u.createElement("option"));a.type="checkbox";z.checkOn=""!==a.value;z.optSelected=b.selected;a=u.createElement("input");a.value="t";a.type="radio";z.radioValue="t"===a.value})();var xa=d.expr.attrHandle;d.fn.extend({attr:function(a,b){return Z(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})}});d.extend({attr:function(a,b,c){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g){if("undefined"===typeof a.getAttribute)return d.prop(a,
b,c);1===g&&d.isXMLDoc(a)||(f=d.attrHooks[b.toLowerCase()]||(d.expr.match.bool.test(b)?Ac:void 0));if(void 0!==c){if(null===c){d.removeAttr(a,b);return}if(f&&"set"in f&&void 0!==(e=f.set(a,c,b)))return e;a.setAttribute(b,c+"");return c}if(f&&"get"in f&&null!==(e=f.get(a,b)))return e;e=d.find.attr(a,b);return null==e?void 0:e}},attrHooks:{type:{set:function(a,b){if(!z.radioValue&&"radio"===b&&E(a,"input")){var c=a.value;a.setAttribute("type",b);c&&(a.value=c);return b}}}},removeAttr:function(a,b){var c,
d=0,f=b&&b.match(T);if(f&&1===a.nodeType)for(;c=f[d++];)a.removeAttribute(c)}});var Ac={set:function(a,b,c){!1===b?d.removeAttr(a,c):a.setAttribute(c,c);return c}};d.each(d.expr.match.bool.source.match(/\w+/g),function(a,b){var c=xa[b]||d.find.attr;xa[b]=function(a,b,d){var e=b.toLowerCase();if(!d){var f=xa[e];xa[e]=g;var g=null!=c(a,b,d)?e:null;xa[e]=f}return g}});var Bc=/^(?:input|select|textarea|button)$/i,Cc=/^(?:a|area)$/i;d.fn.extend({prop:function(a,b){return Z(this,d.prop,a,b,1<arguments.length)},
removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})}});d.extend({prop:function(a,b,c){var e,f=a.nodeType;if(3!==f&&8!==f&&2!==f){if(1!==f||!d.isXMLDoc(a)){b=d.propFix[b]||b;var g=d.propHooks[b]}return void 0!==c?g&&"set"in g&&void 0!==(e=g.set(a,c,b))?e:a[b]=c:g&&"get"in g&&null!==(e=g.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=d.find.attr(a,"tabindex");return b?parseInt(b,10):Bc.test(a.nodeName)||Cc.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor",
"class":"className"}});z.optSelected||(d.propHooks.selected={get:function(a){(a=a.parentNode)&&a.parentNode&&a.parentNode.selectedIndex;return null},set:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=this});d.fn.extend({addClass:function(a){var b,c,e,f,g=0;if(r(a))return this.each(function(b){d(this).addClass(a.call(this,
b,da(this)))});var h=Xa(a);if(h.length)for(;b=this[g++];){var k=da(b);if(c=1===b.nodeType&&" "+L(k)+" "){for(f=0;e=h[f++];)0>c.indexOf(" "+e+" ")&&(c+=e+" ");c=L(c);k!==c&&b.setAttribute("class",c)}}return this},removeClass:function(a){var b,c,e,f,g=0;if(r(a))return this.each(function(b){d(this).removeClass(a.call(this,b,da(this)))});if(!arguments.length)return this.attr("class","");var h=Xa(a);if(h.length)for(;b=this[g++];){var k=da(b);if(c=1===b.nodeType&&" "+L(k)+" "){for(f=0;e=h[f++];)for(;-1<
c.indexOf(" "+e+" ");)c=c.replace(" "+e+" "," ");c=L(c);k!==c&&b.setAttribute("class",c)}}return this},toggleClass:function(a,b){var c=typeof a,e="string"===c||Array.isArray(a);return"boolean"===typeof b&&e?b?this.addClass(a):this.removeClass(a):r(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,da(this),b),b)}):this.each(function(){var b,g;if(e){var h=0;var k=d(this);for(g=Xa(a);b=g[h++];)k.hasClass(b)?k.removeClass(b):k.addClass(b)}else if(void 0===a||"boolean"===c)(b=da(this))&&v.set(this,
"__className__",b),this.setAttribute&&this.setAttribute("class",b||!1===a?"":v.get(this,"__className__")||"")})},hasClass:function(a){var b,c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+L(da(b))+" ").indexOf(a))return!0;return!1}});var Dc=/\r/g;d.fn.extend({val:function(a){var b,c,e=this[0];if(arguments.length){var f=r(a);return this.each(function(c){1===this.nodeType&&(c=f?a.call(this,c,d(this).val()):a,null==c?c="":"number"===typeof c?c+="":Array.isArray(c)&&(c=d.map(c,function(a){return null==
a?"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,c,"value")||(this.value=c))})}if(e){if((b=d.valHooks[e.type]||d.valHooks[e.nodeName.toLowerCase()])&&"get"in b&&void 0!==(c=b.get(e,"value")))return c;c=e.value;return"string"===typeof c?c.replace(Dc,""):null==c?"":c}}});d.extend({valHooks:{option:{get:function(a){var b=d.find.attr(a,"value");return null!=b?b:L(d.text(a))}},select:{get:function(a){var b=a.options,c=a.selectedIndex,e="select-one"===
a.type,f=e?null:[],g=e?c+1:b.length;for(a=0>c?g:e?c:0;a<g;a++){var h=b[a];if(!(!h.selected&&a!==c||h.disabled||h.parentNode.disabled&&E(h.parentNode,"optgroup"))){h=d(h).val();if(e)return h;f.push(h)}}return f},set:function(a,b){for(var c,e,f=a.options,g=d.makeArray(b),h=f.length;h--;)if(e=f[h],e.selected=-1<d.inArray(d.valHooks.option.get(e),g))c=!0;c||(a.selectedIndex=-1);return g}}}});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){if(Array.isArray(b))return a.checked=
-1<d.inArray(d(a).val(),b)}};z.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});z.focusin="onfocusin"in t;var Ob=/^(?:focusinfocus|focusoutblur)$/,Pb=function(a){a.stopPropagation()};d.extend(d.event,{trigger:function(a,b,c,e){var f,g,h,k=[c||u],l=Ka.call(a,"type")?a.type:a;var m=Ka.call(a,"namespace")?a.namespace.split("."):[];var n=h=f=c=c||u;if(3!==c.nodeType&&8!==c.nodeType&&!Ob.test(l+d.event.triggered)){-1<l.indexOf(".")&&(m=l.split("."),l=m.shift(),
m.sort());var q=0>l.indexOf(":")&&"on"+l;a=a[d.expando]?a:new d.Event(l,"object"===typeof a&&a);a.isTrigger=e?2:3;a.namespace=m.join(".");a.rnamespace=a.namespace?new RegExp("(^|\\.)"+m.join("\\.(?:.*\\.|)")+"(\\.|$)"):null;a.result=void 0;a.target||(a.target=c);b=null==b?[a]:d.makeArray(b,[a]);m=d.event.special[l]||{};if(e||!m.trigger||!1!==m.trigger.apply(c,b)){if(!e&&!m.noBubble&&!ma(c)){var p=m.delegateType||l;Ob.test(p+l)||(n=n.parentNode);for(;n;n=n.parentNode)k.push(n),f=n;f===(c.ownerDocument||
u)&&k.push(f.defaultView||f.parentWindow||t)}for(f=0;(n=k[f++])&&!a.isPropagationStopped();)h=n,a.type=1<f?p:m.bindType||l,(g=(v.get(n,"events")||{})[a.type]&&v.get(n,"handle"))&&g.apply(n,b),(g=q&&n[q])&&g.apply&&Oa(n)&&(a.result=g.apply(n,b),!1===a.result&&a.preventDefault());a.type=l;e||a.isDefaultPrevented()||m._default&&!1!==m._default.apply(k.pop(),b)||!Oa(c)||!q||!r(c[l])||ma(c)||((f=c[q])&&(c[q]=null),d.event.triggered=l,a.isPropagationStopped()&&h.addEventListener(l,Pb),c[l](),a.isPropagationStopped()&&
h.removeEventListener(l,Pb),d.event.triggered=void 0,f&&(c[q]=f));return a.result}}},simulate:function(a,b,c){a=d.extend(new d.Event,c,{type:a,isSimulated:!0});d.event.trigger(a,null,b)}});d.fn.extend({trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];if(c)return d.event.trigger(a,b,c,!0)}});z.focusin||d.each({focus:"focusin",blur:"focusout"},function(a,b){var c=function(a){d.event.simulate(b,a.target,d.event.fix(a))};d.event.special[b]=
{setup:function(){var d=this.ownerDocument||this,f=v.access(d,b);f||d.addEventListener(a,c,!0);v.access(d,b,(f||0)+1)},teardown:function(){var d=this.ownerDocument||this,f=v.access(d,b)-1;f?v.access(d,b,f):(d.removeEventListener(a,c,!0),v.remove(d,b))}}});var ya=t.location,Qb=Date.now(),cb=/\?/;d.parseXML=function(a){if(!a||"string"!==typeof a)return null;try{var b=(new t.DOMParser).parseFromString(a,"text/xml")}catch(c){b=void 0}b&&!b.getElementsByTagName("parsererror").length||d.error("Invalid XML: "+
a);return b};var ic=/\[\]$/,Rb=/\r?\n/g,Ec=/^(?:submit|button|image|reset|file)$/i,Fc=/^(?:input|select|textarea|keygen)/i;d.param=function(a,b){var c,e=[],f=function(a,b){var c=r(b)?b():b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(null==c?"":c)};if(Array.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,this.value)});else for(c in a)Ya(c,a[c],b,f);return e.join("&")};d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=
d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!d(this).is(":disabled")&&Fc.test(this.nodeName)&&!Ec.test(a)&&(this.checked||!Kb.test(a))}).map(function(a,b){var c=d(this).val();return null==c?null:Array.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace(Rb,"\r\n")}}):{name:b.name,value:c.replace(Rb,"\r\n")}}).get()}});var Gc=/%20/g,Hc=/#.*$/,Ic=/([?&])_=[^&]*/,Jc=/^(.*?):[ \t]*([^\r\n]*)$/mg,Kc=/^(?:GET|HEAD)$/,Lc=/^\/\//,
Sb={},Za={},Tb="*/".concat("*"),db=u.createElement("a");db.href=ya.href;d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:ya.href,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(ya.protocol),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Tb,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},
responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":JSON.parse,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?$a($a(a,d.ajaxSettings),b):$a(d.ajaxSettings,a)},ajaxPrefilter:Cb(Sb),ajaxTransport:Cb(Za),ajax:function(a,b){function c(a,b,c,g){var l=b;if(!G){G=!0;h&&t.clearTimeout(h);e=void 0;f=g||"";A.readyState=0<a?4:0;g=200<=a&&300>a||304===a;if(c){var p=m;for(var u=A,x,K,C,F,B=p.contents,
E=p.dataTypes;"*"===E[0];)E.shift(),void 0===x&&(x=p.mimeType||u.getResponseHeader("Content-Type"));if(x)for(K in B)if(B[K]&&B[K].test(x)){E.unshift(K);break}if(E[0]in c)C=E[0];else{for(K in c){if(!E[0]||p.converters[K+" "+E[0]]){C=K;break}F||(F=K)}C=C||F}C?(C!==E[0]&&E.unshift(C),p=c[C]):p=void 0}a:{c=m;x=p;K=A;C=g;var I;u={};B=c.dataTypes.slice();if(B[1])for(O in c.converters)u[O.toLowerCase()]=c.converters[O];for(F=B.shift();F;){c.responseFields[F]&&(K[c.responseFields[F]]=x);!H&&C&&c.dataFilter&&
(x=c.dataFilter(x,c.dataType));var H=F;if(F=B.shift())if("*"===F)F=H;else if("*"!==H&&H!==F){var O=u[H+" "+F]||u["* "+F];if(!O)for(I in u)if(p=I.split(" "),p[1]===F&&(O=u[H+" "+p[0]]||u["* "+p[0]])){!0===O?O=u[I]:!0!==u[I]&&(F=p[0],B.unshift(p[1]));break}if(!0!==O)if(O&&c["throws"])x=O(x);else try{x=O(x)}catch(mc){p={state:"parsererror",error:O?mc:"No conversion from "+H+" to "+F};break a}}}p={state:"success",data:x}}if(g)if(m.ifModified&&((l=A.getResponseHeader("Last-Modified"))&&(d.lastModified[M]=
l),(l=A.getResponseHeader("etag"))&&(d.etag[M]=l)),204===a||"HEAD"===m.type)l="nocontent";else if(304===a)l="notmodified";else{l=p.state;var N=p.data;var L=p.error;g=!L}else if(L=l,a||!l)l="error",0>a&&(a=0);A.status=a;A.statusText=(b||l)+"";g?r.resolveWith(n,[N,l,A]):r.rejectWith(n,[A,l,L]);A.statusCode(z);z=void 0;k&&q.trigger(g?"ajaxSuccess":"ajaxError",[A,m,g?N:L]);v.fireWith(n,[A,l]);k&&(q.trigger("ajaxComplete",[A,m]),--d.active||d.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=void 0);
b=b||{};var e,f,g,h,k,l,m=d.ajaxSetup({},b),n=m.context||m,q=m.context&&(n.nodeType||n.jquery)?d(n):d.event,r=d.Deferred(),v=d.Callbacks("once memory"),z=m.statusCode||{},E={},I={},H="canceled",A={readyState:0,getResponseHeader:function(a){var b;if(G){if(!g)for(g={};b=Jc.exec(f);)g[b[1].toLowerCase()]=b[2];b=g[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return G?f:null},setRequestHeader:function(a,b){null==G&&(a=I[a.toLowerCase()]=I[a.toLowerCase()]||a,E[a]=b);return this},
overrideMimeType:function(a){null==G&&(m.mimeType=a);return this},statusCode:function(a){var b;if(a)if(G)A.always(a[A.status]);else for(b in a)z[b]=[z[b],a[b]];return this},abort:function(a){a=a||H;e&&e.abort(a);c(0,a);return this}};r.promise(A);m.url=((a||m.url||ya.href)+"").replace(Lc,ya.protocol+"//");m.type=b.method||b.type||m.method||m.type;m.dataTypes=(m.dataType||"*").toLowerCase().match(T)||[""];if(null==m.crossDomain){var B=u.createElement("a");try{B.href=m.url,B.href=B.href,m.crossDomain=
db.protocol+"//"+db.host!==B.protocol+"//"+B.host}catch(K){m.crossDomain=!0}}m.data&&m.processData&&"string"!==typeof m.data&&(m.data=d.param(m.data,m.traditional));Db(Sb,m,b,A);if(G)return A;(k=d.event&&m.global)&&0===d.active++&&d.event.trigger("ajaxStart");m.type=m.type.toUpperCase();m.hasContent=!Kc.test(m.type);var M=m.url.replace(Hc,"");m.hasContent?m.data&&m.processData&&0===(m.contentType||"").indexOf("application/x-www-form-urlencoded")&&(m.data=m.data.replace(Gc,"+")):(B=m.url.slice(M.length),
m.data&&(m.processData||"string"===typeof m.data)&&(M+=(cb.test(M)?"&":"?")+m.data,delete m.data),!1===m.cache&&(M=M.replace(Ic,"$1"),B=(cb.test(M)?"&":"?")+"_="+Qb++ +B),m.url=M+B);m.ifModified&&(d.lastModified[M]&&A.setRequestHeader("If-Modified-Since",d.lastModified[M]),d.etag[M]&&A.setRequestHeader("If-None-Match",d.etag[M]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&A.setRequestHeader("Content-Type",m.contentType);A.setRequestHeader("Accept",m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?
m.accepts[m.dataTypes[0]]+("*"!==m.dataTypes[0]?", "+Tb+"; q=0.01":""):m.accepts["*"]);for(l in m.headers)A.setRequestHeader(l,m.headers[l]);if(m.beforeSend&&(!1===m.beforeSend.call(n,A,m)||G))return A.abort();H="abort";v.add(m.complete);A.done(m.success);A.fail(m.error);if(e=Db(Za,m,b,A)){A.readyState=1;k&&q.trigger("ajaxSend",[A,m]);if(G)return A;m.async&&0<m.timeout&&(h=t.setTimeout(function(){A.abort("timeout")},m.timeout));try{var G=!1;e.send(E,c)}catch(K){if(G)throw K;c(-1,K)}}else c(-1,"No Transport");
return A},getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,void 0,b,"script")}});d.each(["get","post"],function(a,b){d[b]=function(a,e,f,g){r(e)&&(g=g||f,f=e,e=void 0);return d.ajax(d.extend({url:a,type:b,dataType:g,data:e,success:f},d.isPlainObject(a)&&a))}});d._evalUrl=function(a){return d.ajax({url:a,type:"GET",dataType:"script",cache:!0,async:!1,global:!1,"throws":!0})};d.fn.extend({wrapAll:function(a){this[0]&&(r(a)&&(a=a.call(this[0])),a=d(a,this[0].ownerDocument).eq(0).clone(!0),
this[0].parentNode&&a.insertBefore(this[0]),a.map(function(){for(var a=this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this));return this},wrapInner:function(a){return r(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?c.wrapAll(a):b.append(a)})},wrap:function(a){var b=r(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(a){this.parent(a).not("body").each(function(){d(this).replaceWith(this.childNodes)});
return this}});d.expr.pseudos.hidden=function(a){return!d.expr.pseudos.visible(a)};d.expr.pseudos.visible=function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)};d.ajaxSettings.xhr=function(){try{return new t.XMLHttpRequest}catch(a){}};var Mc={0:200,1223:204},ka=d.ajaxSettings.xhr();z.cors=!!ka&&"withCredentials"in ka;z.ajax=ka=!!ka;d.ajaxTransport(function(a){var b,c;if(z.cors||ka&&!a.crossDomain)return{send:function(d,f){var e,h=a.xhr();h.open(a.type,a.url,a.async,a.username,
a.password);if(a.xhrFields)for(e in a.xhrFields)h[e]=a.xhrFields[e];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");for(e in d)h.setRequestHeader(e,d[e]);b=function(a){return function(){b&&(b=c=h.onload=h.onerror=h.onabort=h.ontimeout=h.onreadystatechange=null,"abort"===a?h.abort():"error"===a?"number"!==typeof h.status?f(0,"error"):f(h.status,h.statusText):f(Mc[h.status]||h.status,h.statusText,"text"!==
(h.responseType||"text")||"string"!==typeof h.responseText?{binary:h.response}:{text:h.responseText},h.getAllResponseHeaders()))}};h.onload=b();c=h.onerror=h.ontimeout=b("error");void 0!==h.onabort?h.onabort=c:h.onreadystatechange=function(){4===h.readyState&&t.setTimeout(function(){b&&c()})};b=b("abort");try{h.send(a.hasContent&&a.data||null)}catch(k){if(b)throw k;}},abort:function(){b&&b()}}});d.ajaxPrefilter(function(a){a.crossDomain&&(a.contents.script=!1)});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},
contents:{script:/\b(?:java|ecma)script\b/},converters:{"text script":function(a){d.globalEval(a);return a}}});d.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c;return{send:function(e,f){b=d("<script>").prop({charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&f("error"===a.type?404:200,a.type)});u.head.appendChild(b[0])},abort:function(){c&&c()}}}});
var Ub=[],eb=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=Ub.pop()||d.expando+"_"+Qb++;this[a]=!0;return a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var e,f=!1!==a.jsonp&&(eb.test(a.url)?"url":"string"===typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&eb.test(a.data)&&"data");if(f||"jsonp"===a.dataTypes[0]){var g=a.jsonpCallback=r(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;f?a[f]=a[f].replace(eb,"$1"+g):!1!==a.jsonp&&
(a.url+=(cb.test(a.url)?"&":"?")+a.jsonp+"="+g);a.converters["script json"]=function(){e||d.error(g+" was not called");return e[0]};a.dataTypes[0]="json";var h=t[g];t[g]=function(){e=arguments};c.always(function(){void 0===h?d(t).removeProp(g):t[g]=h;a[g]&&(a.jsonpCallback=b.jsonpCallback,Ub.push(g));e&&r(h)&&h(e[0]);e=h=void 0});return"script"}});z.createHTMLDocument=function(){var a=u.implementation.createHTMLDocument("").body;a.innerHTML="<form></form><form></form>";return 2===a.childNodes.length}();
d.parseHTML=function(a,b,c){if("string"!==typeof a)return[];"boolean"===typeof b&&(c=b,b=!1);if(!b)if(z.createHTMLDocument){b=u.implementation.createHTMLDocument("");var e=b.createElement("base");e.href=u.location.href;b.head.appendChild(e)}else b=u;e=Hb.exec(a);c=!c&&[];if(e)return[b.createElement(e[1])];e=mb([a],b,c);c&&c.length&&d(c).remove();return d.merge([],e.childNodes)};d.fn.load=function(a,b,c){var e,f,g=this,h=a.indexOf(" ");if(-1<h){var k=L(a.slice(h));a=a.slice(0,h)}r(b)?(c=b,b=void 0):
b&&"object"===typeof b&&(e="POST");0<g.length&&d.ajax({url:a,type:e||"GET",dataType:"html",data:b}).done(function(a){f=arguments;g.html(k?d("<div>").append(d.parseHTML(a)).find(k):a)}).always(c&&function(a,b){g.each(function(){c.apply(this,f||[a.responseText,b,a])})});return this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.expr.pseudos.animated=function(a){return d.grep(d.timers,function(b){return a===
b.elem}).length};d.offset={setOffset:function(a,b,c){var e=d.css(a,"position"),f=d(a),g={};"static"===e&&(a.style.position="relative");var h=f.offset();var k=d.css(a,"top");var l=d.css(a,"left");("absolute"===e||"fixed"===e)&&-1<(k+l).indexOf("auto")?(l=f.position(),k=l.top,l=l.left):(k=parseFloat(k)||0,l=parseFloat(l)||0);r(b)&&(b=b.call(a,c,d.extend({},h)));null!=b.top&&(g.top=b.top-h.top+k);null!=b.left&&(g.left=b.left-h.left+l);"using"in b?b.using.call(a,g):f.css(g)}};d.fn.extend({offset:function(a){if(arguments.length)return void 0===
a?this:this.each(function(b){d.offset.setOffset(this,a,b)});var b;if(b=this[0]){if(!b.getClientRects().length)return{top:0,left:0};var c=b.getBoundingClientRect();b=b.ownerDocument.defaultView;return{top:c.top+b.pageYOffset,left:c.left+b.pageXOffset}}},position:function(){if(this[0]){var a,b=this[0],c={top:0,left:0};if("fixed"===d.css(b,"position"))var e=b.getBoundingClientRect();else{e=this.offset();var f=b.ownerDocument;for(a=b.offsetParent||f.documentElement;a&&(a===f.body||a===f.documentElement)&&
"static"===d.css(a,"position");)a=a.parentNode;a&&a!==b&&1===a.nodeType&&(c=d(a).offset(),c.top+=d.css(a,"borderTopWidth",!0),c.left+=d.css(a,"borderLeftWidth",!0))}return{top:e.top-c.top-d.css(b,"marginTop",!0),left:e.left-c.left-d.css(b,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===d.css(a,"position");)a=a.offsetParent;return a||Pa})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===
b;d.fn[a]=function(d){return Z(this,function(a,d,e){if(ma(a))var f=a;else 9===a.nodeType&&(f=a.defaultView);if(void 0===e)return f?f[b]:a[d];f?f.scrollTo(c?f.pageXOffset:e,c?e:f.pageYOffset):a[d]=e},a,d,arguments.length)}});d.each(["top","left"],function(a,b){d.cssHooks[b]=ub(z.pixelPosition,function(a,e){if(e)return e=sa(a,b),Ua.test(e)?d(a).position()[b]+"px":e})});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(f,
g){var h=arguments.length&&(c||"boolean"!==typeof f),k=c||(!0===f||!0===g?"margin":"border");return Z(this,function(b,c,f){return ma(b)?0===e.indexOf("outer")?b["inner"+a]:b.document.documentElement["client"+a]:9===b.nodeType?(c=b.documentElement,Math.max(b.body["scroll"+a],c["scroll"+a],b.body["offset"+a],c["offset"+a],c["client"+a])):void 0===f?d.css(b,c,k):d.style(b,c,f,k)},b,h?f:void 0,h)}})});d.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu".split(" "),
function(a,b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});d.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});d.proxy=function(a,b){if("string"===typeof b){var c=a[b];b=a;a=
c}if(r(a)){var e=ea.call(arguments,2);c=function(){return a.apply(b||this,e.concat(ea.call(arguments)))};c.guid=a.guid=a.guid||d.guid++;return c}};d.holdReady=function(a){a?d.readyWait++:d.ready(!0)};d.isArray=Array.isArray;d.parseJSON=JSON.parse;d.nodeName=E;d.isFunction=r;d.isWindow=ma;d.camelCase=U;d.type=la;d.now=Date.now;d.isNumeric=function(a){var b=d.type(a);return("number"===b||"string"===b)&&!isNaN(a-parseFloat(a))};"function"===typeof define&&define.amd&&define("jquery",[],function(){return d});
var Nc=t.jQuery,Oc=t.$;d.noConflict=function(a){t.$===d&&(t.$=Oc);a&&t.jQuery===d&&(t.jQuery=Nc);return d};ba||(t.jQuery=t.$=d);return d});